site_name: VergeOS Docs
site_url: https://docs.verge.io
repo_url: https://github.com/verge-io/docs
repo_name: verge-io/docs
edit_uri: edit/main/docs/


theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/vergelogomark.svg
  favicon: assets/vergelogomark.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.indexes
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    - navigation.footer
    - navigation.path
    - content.action.edit  # Shows the edit button
    - content.action.view  # Shows the view source button
  language: en
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - blog:
      blog_dir: knowledge-base
      post_url_format: "{slug}"
      blog_toc: true
      archive: false
      pagination_per_page: 50
  - search:
      prebuild_index: true
      lang:
      - en
  - glightbox
markdown_extensions:
  - sane_lists
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - footnotes
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 2

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VergeIO_Inc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/verge-io/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnFu28s0GBVi18j7Ez3MXRg
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@verge.io
    - icon: fontawesome/solid/phone
      link: tel:855-855-8300
  generator: false
  analytics:
      provider: google
      property: G-KBH6Q02QFH
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  status:
    new: Recently added
    deprecated: Deprecated

extra_javascript:
  - javascripts/extra.js

#extra_css:
#  - stylesheets/extra.css

copyright: |
  Copyright &copy; 2024 <a href="https://verge.io" target="_blank" rel="noopener"> Verge.io</a> |
  <a href="#__consent">Change cookie settings</a>

nav:
- Home: index.md
- Implementation Guide:
  - Intro: implementation-guide/intro.md
  - Core Concepts: implementation-guide/concepts.md
  - Node Sizing: implementation-guide/sizing.md
  - Network Design: implementation-guide/network-design.md
  - Installation:
    - Pre-Installation: implementation-guide/pre-installation.md
    - Bootable Media: implementation-guide/install-media.md
    - Installation: implementation-guide/installation-guide.md
    - Post-Installation: implementation-guide/post-installation.md
  - Install Additional Nodes:
    - Scale Out Nodes: implementation-guide/scale-out-nodes.md
    - Compute Nodes: implementation-guide/compute-nodes.md
    - Storage Nodes: implementation-guide/storage-nodes.md
  - Reference Architecture:
    - Edge / ROBO: reference-architecture/edge.md
    - Cloud Providers: reference-architecture/csp.md
    - Life / Data Science: reference-architecture/data-science.md
    - Homelab: reference-architecture/homelab.md
- Knowledge Base:
  - knowledge-base/index.md
- Product Guide:
  - Overview:
    - What is VergeOS?: product-guide/what-is-vergeos.md
    - VergeOS User Interface: product-guide/ui-overview.md
    - Architecture: product-guide/vsan/architecture.md
  - What's New:
    - Release Notes: release-notes/release-notes.md
    - Changelog: release-notes/release-notes-overview.md
  - Concepts:
    - vSAN Architecture: product-guide/vsan/architecture.md
    - Storage Tiers: product-guide/vsan/storage-tiers.md
    - Network Design: product-guide/networks/network-overview.md
  - System Management:
    - Settings Overview: product-guide/system/settings-overview.md
    - Licensing and Updates: product-guide/system/licensing-and-updates.md
    - Advanced Settings: product-guide/system/advanced-system-settings.md
    - User Management:
      - Users and Groups: product-guide/system/users-groups.md
      - Permissions: product-guide/system/permissions.md
    - Certificates: product-guide/system/certificates.md
    - Sites Dashboard:
      - Overview: product-guide/system/sites-overview.md
      - Adding Sites: product-guide/system/site-dashboard-add-sites.md
    - Clusters:
      - Overview: product-guide/system/clusters.md
      - Configuration Options: product-guide/system/clusters-config-options.md
      - Nodes:
        - Overview: product-guide/system/nodes-overview.md
        - IPMI: product-guide/system/ipmi.md
        - System Event Log (SEL): product-guide/system/sel.md
        - Maintenance Mode: product-guide/system/maintenance-mode.md
        - Drive Replacement: product-guide/system/drive-replacement.md
    - Storage:
      - Storage Tiers: product-guide/vsan/storage-tiers.md
      - Preferred Tier: product-guide/vsan/preferred-tiers.md
      - Media Images: product-guide/vsan/uploading-files-to-vsan.md
      - Removing ISO References: product-guide/vsan/removing-iso-refs.md
    - Networks:
      - Overview: product-guide/networks/network-overview.md
      - Network Types:
        - Internal Networks: product-guide/networks/internal-networks.md
        - External Networks: product-guide/networks/connect-lan-wan.md
        - Layer 2 Networks: product-guide/networks/internal-layer2.md
        - Layer 3 Networks: product-guide/networks/internal-layer3.md
      - Configuration:
        - Network Rules: product-guide/networks/network-rules.md
        - Aliases: product-guide/networks/aliases.md
        - DHCP Configuration: product-guide/networks/dhcp-static-lease.md
        - NAT Configuration: product-guide/networks/nat-1to1.md
        - VLANs: product-guide/networks/create-vlan.md
        - Bonded VLANs: product-guide/networks/bonded-vlans.md
        - External IP Assignment: product-guide/networks/assign-external-ip.md
      - Monitoring:
        - Network Dashboards: product-guide/networks/network-dashboards.md
        - Tracking Statistics: product-guide/networks/tracking-net-statistics.md
        - Port Mirroring: product-guide/networks/port-mirroring.md
        - Network Diagnostics Tool: product-guide/networks/net-diagnostics.md
      - VPN:
        - Overview: product-guide/vpn/vpn-overview.md
        - IPSec: product-guide/vpn/ipsec.md
        - WireGuard: product-guide/vpn/wireguard-config.md
        - WireGuard Examples: product-guide/vpn/wireguard-examples.md
    - Device Passthrough:
      - Overview: product-guide/system/device-pass-overview.md
      - NVIDIA vGPU: product-guide/system/nvidia-vgpu.md
      - SR-IOV NIC: product-guide/system/sriov-nics.md
      - USB Passthrough: product-guide/system/usb-passthrough.md
      - One-to-One PCI Passthrough: product-guide/system/generic-pci-passthrough.md
  - Workload Management:
    - Virtual Machines:
      - Best Practices: product-guide/virtual-machines/vm-best-practices.md
      - Creating VMs: product-guide/virtual-machines/creating-vms.md
      - VM Configuration:
        - VM Fields: product-guide/virtual-machines/vm-field-descriptions.md
        - VM Drives: product-guide/virtual-machines/vm-drives.md
        - VM Network Interfaces: product-guide/virtual-machines/vm-nics.md
        - VM Guest Agent: product-guide/virtual-machines/vm-guest-agent.md
      - VM Operations:
        - Working With VMs: product-guide/virtual-machines/working-with-vms.md
        - Live Migrations: product-guide/virtual-machines/live-migrations.md
        - Remote Console: product-guide/virtual-machines/vm-remote-console.md
      - Importing VMs: 
        - Overview: product-guide/virtual-machines/import-vms.md
        - From Media Images: product-guide/virtual-machines/import-from-upload.md
        - From VMware Backup: product-guide/virtual-machines/import-from-vmware.md
        - From NAS Volume: product-guide/virtual-machines/import-from-nas.md
        - Viewing Import Jobs: product-guide/virtual-machines/view-import-jobs.md
      - VM Export: product-guide/virtual-machines/vm-export-volume.md
      - VDI:
        - Overview: product-guide/virtual-machines/vdi-overview.md
        - VDI Administrator: product-guide/virtual-machines/vdi-administrator.md
        - VDI User: product-guide/virtual-machines/vdi-user.md
      - Guest OS Compatibility: product-guide/virtual-machines/guest-os-compatibility.md
    - Tenants:
      - Creating Tenants: product-guide/tenants/create-tenants.md
      - Resource Management:
        - Increasing Resources: product-guide/tenants/add-tenant-resources.md
        - Reducing Resources: product-guide/tenants/reduce-tenant-resources.md
      - Tenant Operations:
        - Modifying Tenants: product-guide/tenants/tenant-modifications.md
        - Monitoring Tenants: product-guide/tenants/tenant-monitoring.md
        - Assigning External IPs: product-guide/tenants/assign-ip-to-tenant.md
        - Sharing Files: product-guide/tenants/provide-files-to-tenant.md
        - Sharing VMs: product-guide/tenants/share-vm-snapshot.md
      - Usage Reports: product-guide/tenants/tenant-usagereports.md
    - NAS:
      - Overview: product-guide/nas/nas-service.md
      - Volumes:
        - Local Volumes: product-guide/nas/nas-local-volumes.md
        - Remote Volumes: product-guide/nas/nas-remote-volumes.md
        - Volume Snapshots: product-guide/nas/volume-snapshots-restores.md
        - Volume Syncs: product-guide/nas/volume-syncs.md
      - Shares: product-guide/nas/nas-shares.md
      - Active Directory: product-guide/nas/nas-join-ad-domain.md
  - Backup & Disaster Recovery:
    - Snapshots:
      - Overview: product-guide/backup-dr/snapshots-overview.md
      - Profiles: product-guide/backup-dr/snapshot-profiles.md
      - Cloud Snapshots: product-guide/backup-dr/cloud-snapshot-restore.md
      - VM Snapshots: product-guide/backup-dr/vm-snapshots-restores.md
      - Tenant Snapshots: product-guide/tenants/tenant-snapshots.md
      - Tenant Restores: product-guide/tenants/tenant-restores.md
    - Site Syncs:
      - Configuration: product-guide/backup-dr/sync-configuration.md
      - Monitoring: product-guide/backup-dr/monitoring-site-syncs.md
      - Sync Back: product-guide/backup-dr/sync-back.md
      - Manual Sync: product-guide/backup-dr/manual-site-syncs.md
    - Repair Server: product-guide/backup-dr/repair-server.md
  - Security:
    - Authentication:
      - Overview: product-guide/auth/auth-sources-overview.md
      - Entra ID / Azure AD: product-guide/auth/azure-auth.md
      - Google: product-guide/auth/google-auth.md
      - Multi-Factor Authentication: product-guide/auth/mfa-email.md
      - OIDC Applications: product-guide/auth/oidc-apps-overview.md
    - Permissions Management: product-guide/system/permissions.md
  - Monitoring & Observability:
    - Subscriptions & Alerts:
      - Creating Subscriptions: product-guide/system/subscriptions-overview.md
      - Subscription Profiles: product-guide/system/subscription-profiles.md
      - Accessing Subscriptions: product-guide/system/subscriptions-accessing.md
    - Site Dashboard: product-guide/system/sites-overview.md
    - Network Statistics: product-guide/networks/tracking-net-statistics.md
    - Tenant Monitoring: product-guide/tenants/tenant-monitoring.md
  - Automation:
    - Task Manager:
      - Overview: product-guide/automation/task-manager.md
      - Create Tasks: product-guide/automation/create-tasks.md
    - Recipes:
      - Organization: product-guide/automation/recipes-organization.md
      - VM Recipes: product-guide/automation/vm-recipes.md
      - Tenant Recipes: product-guide/automation/tenant-recipes.md
  - Troubleshooting:
    - Network Troubleshooting: product-guide/networks/net-troubleshooting.md
    - System Event Logs: product-guide/system/sel.md
    - Drive Replacement: product-guide/system/drive-replacement.md
    - Storage Issues: product-guide/vsan/removing-iso-refs.md
  - Integrations:
    - Storware: what-is-storware.md
    - VMware: api.md
    - Inuvika: what-is-inuvika.md
  - Reference:
    - Glossary: glossary.md
    - API: api.md
- Release Notes: 
  - Overview: release-notes/release-notes-overview.md
  - 4.13 (latest): release-notes/release-notes.md
  - 4.12: release-notes/4-12-release-notes.md
  - 4.11: release-notes/4-11-release-notes.md
  - "4.10": release-notes/4-10-release-notes.md
  - 4.9: release-notes/4-9-release-notes.md

#build
